Adding another resource available on youtube
zero-to-mastery/resources pull request #706
Opened 2021-07-09 03:34 UTC by shehroze-1122

Hi, I added another great resource for developers available on youtube. Kindly review and add. I have added additional details in the .md file as well.

2021-07-27 12:28 UTC, CodingSpecies requested changes

2021-07-27 12:28 UTC, CodingSpecies commented on YouTubeChannels.md
> +* [Clément Mihailescu](https://www.youtube.com/channel/UCaO6VoaYJv4kS-TQO_M-N_g): An Ex-Google Software Engineer, an Ex-Facebook Software Engineer, and the CEO and co-founder of AlgoExpert (algoexper
![image](https://user-images.githubusercontent.com/70807500/127153275-0a6f5b6e-6380-43ef-9832-a8e86c1d7351.png)
@shehroze1  There seems to be a typo, as seen in the above screenshot, where there seems to be a `!.` Please either remove the `.` or the `!`. Thank you.

2021-07-29 06:04 UTC, shehroze-1122 commented
Thank you for pointing it out. Now it is corrected!

2021-07-29 07:20 UTC, CodingSpecies approved these changes
LGTM, thank you!

2021-08-03 17:39 UTC, arjunkharbanda commented
The build is failing so I am sorry I have to close this PR please Re-submit if you can

2021-08-03 17:39 UTC, closed without merging