Added two new JavaScript resources
zero-to-mastery/resources pull request #911
Opened 2023-02-17 09:43 UTC by codeguage-code

## Resource name and link

[Comprehensive JavaScript Course - CodeGuage](https://www.codeguage.com/courses/js/)

## Short description

A detailed course on JavaScript, covering numerous aspects of the language, with 15 units (modules), almost 80 chapters, 25 quizzes, and over 50 exercises.

## Why do you think this is a good resource?

First of all, the resource is absolutely free of cost. There's even no need to sign up to access the content. In addition to this, unlike many free resources out there, the chapters go in extensive detail and offer top-notch, high-quality content, both easy to read and easy to understand.

## GitHub repository (optional)

2023-02-18 08:52 UTC, AvidCoder101 approved these changes
LGTM!

2023-03-07 05:41 UTC, CBID2 commented on JavaScript.md
>  - [A brief history of JavaScript](https://medium.com/@benastontweet/lesson-1a-the-history-of-javascript-8c1ce3bffb17) by Ben Aston: It is a medium article describing and throwing light upon the Histo
```suggestion
- [A brief history of JavaScript](https://medium.com/@benastontweet/lesson-1a-the-history-of-javascript-8c1ce3bffb17) by Ben Aston: It is a Medium article describing and throwing light upon the History of JavaScript.
```

2023-03-07 05:44 UTC, CBID2 commented on JavaScript.md
>  - [FreeCodeCamp Beginning JavaScript](https://www.freecodecamp.org/): Learn JavaScript with an online community, examples, and tons of more advanced JavaScript topics when you are done. Certificate a
```suggestion
- [FreeCodeCamp Beginning JavaScript](https://www.freecodecamp.org/): Learn JavaScript with an online community, examples, and tons of more advanced JavaScript topics. Best part is: you get a certificate and it's all free!
```

2023-03-07 05:46 UTC, CBID2 commented on JavaScript.md
>  - [Exploring JS: JavaScript books for programmers](http://exploringjs.com/) by Dr. Axel Rauschmeyer: free online books that delve deep into the Javascript language - always up-to-date with new books
```suggestion
- [Exploring JS: JavaScript books for programmers](http://exploringjs.com/) by Dr. Axel Rauschmeyer: This free online book series devels deep into the Javascript language. The best part: It's always up-to-date with new books on the latest Ecmascript features!
```

2023-03-07 05:48 UTC, CBID2 requested changes
Hi @codeguage-code! 😄 I added some suggestions to make your descriptions a bit clearer. I hope you find them helpful! 😄

2023-05-03 09:09 UTC, merged