added 2 podcasts and added name to contributors
zero-to-mastery/resources pull request #915
Opened 2023-03-03 03:52 UTC by danithang

## Resource name and link

## Short description

## Why do you think this is a good resource?

## GitHub repository (optional)

2023-03-09 23:25 UTC, danithang commented on Podcasts.md
> +- [HTML All The Things](https://www.htmlallthethings.com/podcast): Join hosts as they dive head first into the world of web development and design. In this show they discuss running a small business,
Thank you, that is a better description.

2023-03-10 04:26 UTC, CBID2 commented on Podcasts.md
> +- [HTML All The Things](https://www.htmlallthethings.com/podcast): Join hosts Matt Lawrence and Mike Karan as they dive head first into the world of web development and design. In this show,they disc
```suggestion
- [HTML All The Things](https://www.htmlallthethings.com/podcast): Join hosts Matt Lawrence and Mike Karan as they dive into the world of web development and design. In this show, they discuss running a small business and making websites and web apps for customers from all over the industry.  Matt and Mike also take a deep dive into things like their latest projects, their business strategies, and much more! 
```

2023-03-10 04:27 UTC, CBID2 approved these changes
Hi @danithang! :) I just made a few more changes.

2023-05-03 09:05 UTC, LaurelineP requested changes

2023-05-03 09:05 UTC, LaurelineP commented on Podcasts.md
> +- [HTML All The Things](https://www.htmlallthethings.com/podcast): Join hosts Matt Lawrence and Mike Karan as they dive into the world of web development and design. In this show, they discuss runnin
Regarding the following:  
`they discuss running a small business and making websites and web apps for customers from all over the industry.`

Could be improved with the following - avoiding repetitive use of  "and"
`they discuss running a small business, making websites and web apps for customers from all over the industry.`

2023-05-05 00:54 UTC, danithang commented on Podcasts.md
> +- [HTML All The Things](https://www.htmlallthethings.com/podcast): Join hosts Matt Lawrence and Mike Karan as they dive into the world of web development and design. In this show, they discuss runnin
Yeah that sounds better.

2023-05-05 01:03 UTC, danithang reviewed
Changed a sentence to sound better

2023-07-21 13:31 UTC, merged